apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-boot-poc.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "spring-boot-poc.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s